{% set name = "mmhash3" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mmhash3-{{ version }}.tar.gz
  sha256: a00d68f4a1cc434b9501513c8a29e18ed1ddad383677d72b41d71d0d862348af

build:
  noarch: generic
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 3

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}

  host:
    - python >3.7
    - pip
    - setuptools
  run:
    - python >3.7

test:
  imports:
    - mmh3
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Fokko/mmhash3
  summary: Python wrapper for MurmurHash (MurmurHash3), a set of fast and robust hash functions.
  license: CC0-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
